export const COMPLIMENTS = {
  en: [
    "Your voice is as beautiful as a chorus of angels",
    "Your eyes shine like the stars in the night sky",
    "Your hair flows like the waters of the Vistula",
    "Your laughter rings through the air like the church bells of Kraków",
    "Your smile brings joy to everyone around you",
    "Your ears look like freshly made pierogi",
    "You are a really sweet person",
    "You don’t look one day older than 35!",
  ],
  pl: ["Kiedy babcia Eva patrzy z nieba, z pewnością jest dumna", "Twoja herbatka jest dobra na wszystk"],
  de: [
    "Deine Grossherzigkeit unterscheidet dich von anderen Menschen",
    "Heute denken wir an dich",
    "Mögest du heute auch erfahren wie schön deine Seele ist",
    "Von allen Mamas hast du den besten Geschmack",
    "Wem wirst du heute ein Lächeln aufs Gesicht zaubern?",
    "Dein Duft ist wie 1000 wilde Rosen",
    "Dein Drang die Welt besser zu machen ziert dich",
    "Deine Wärme strahlt auf alle Menschen in deiner Nähe",
    "Menschen fühlen sich zu dir hingezogen weil du aufrichtig und gut bist",
    "Fühle die Verbundenheit und Einheit mit allen Frauen- deinen Urmüttern, Müttern, Schwestern, Töchtern und Freundinnen",
    "Du bist ein wunderbarer und notwendiger Teil des Ganzen",
    "Deine Witze sind die lustigsten und inspirierendsten",
    "Masz najlepszy smak herbatek",
    "Du begegnest jeden Menschen mit Respekt und dafür lieben wir dich",
    "Du bist immer anwesend in den Menschen die dich kennen und lieben",
    "Du probierst in jedem Menschen das Gute zu sehen und das spürt man",
    "Menschen fühlen sich zu dir hingezogen weil du ihr Vertrauen weckst",
    "Ich hoffe dass du heute so liebevoll und grossherzig mit dir selbst umgehst wie du mit anderen umgehst",
    "Du bist eine Top Frau, Mutter, Tochter, Schwester und Freundin!",
    "Ich liebe dich und denke jeden Tag an dich",
    "Ich bin stolz auf dich weil du all deine Rollen so gut meisterst",
    "Du bist sehr sensibel und das ist deine Gabe und Kraft",
    "Du bist immer da",
    "Du hast 2 Menschen ein Leben geschenkt wofür sie dich immer lieben",
    "Du bist für uns die schönste Mama der Welt",
    "Dich im Leben zu haben ist ein Geschenk",
    "Du hast uns über eine Million Glücksmomente beschert’",
    "Ich hoffe du findest dich genauso schön wie wir",
    "Sehe dich selbst als eine Königin",
    "Ich bewundere deine Hilfsbereitschaft",
    "Deine Stimme zu hören ist wohltuend",
    "Du bist der wichtigste Mensch für uns",
    "Ich bin stolz darauf dich als Mutter zu haben",
    "Du bist eine Inspiration für deine Mitmenschen",
    "Du bist immer schön",
    "Dein Lachen macht dich am schönsten",
    "Ich würde dich niemals gegen eine andere Mama tauschen",
    "Deine Seele ist wundervoll",
    "Du bist immer genug",
    "Mögest du heute schöne Verbindungen haben",
    "Mögest du dich heute in dich selbst verlieben",
  ],
}
